FROM python:3.12-slim

WORKDIR /app

# Копируем содержимое MessengerGoga прямо в /app
COPY ./MessengerGoga/ .

RUN pip install --no-cache-dir -r requirements.txt

# Теперь asgi.py доступен без префикса
CMD ["uvicorn", "asgi:application", "--host", "0.0.0.0", "--port", "8080"]
