# Generated by Django 6.0.3 on 2026-03-29 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='Название')),
            ],
        ),
        migrations.RemoveField(
            model_name='chat',
            name='ChatDMChannel',
        ),
        migrations.AddField(
            model_name='chat',
            name='chat_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='talking.chattype', verbose_name='Тип чата'),
        ),
    ]
