# Generated by Django 6.0.3 on 2026-04-22 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chattype',
            name='name',
            field=models.CharField(default=1, max_length=72, unique=True, verbose_name='Название'),
        ),
    ]
