# Generated by Django 6.0.3 on 2026-03-19 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talking', '0002_alter_user_name_alter_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='Название')),
                ('creation_date', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('ChatDMChannel', models.CharField(max_length=1, verbose_name='Чат, лс или канал')),
                ('chat_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talkinb', to='talking.user', verbose_name='Создатель чата')),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sending_date', models.DateTimeField(auto_now=True, verbose_name='Дата отправки')),
                ('message_words', models.CharField(max_length=4096, verbose_name='Сообщение')),
                ('message_file', models.BinaryField(verbose_name='Файл')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talking', to='talking.user', verbose_name='Автор')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talking', to='talking.chats', verbose_name='Чат')),
            ],
        ),
    ]
