# Generated by Django 6.0.3 on 2026-03-30 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talking', '0002_chattype_remove_chat_chatdmchannel_chat_chat_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='chat_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='talking.chattype', verbose_name='Тип чата'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chattype',
            name='name',
            field=models.CharField(default=1, max_length=32, unique=True, verbose_name='Название'),
        ),
    ]
