# Generated by Django 6.0.3 on 2026-04-11 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talking', '0005_alter_chat_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='message_file',
            field=models.TextField(verbose_name='Файл'),
        ),
    ]
