# Generated by Django 6.0.3 on 2026-04-14 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talking', '0006_alter_chatmessage_message_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='message_file',
            field=models.BinaryField(editable=True, verbose_name='Файл'),
        ),
    ]
